package com.gracefeed.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val LightColorScheme = lightColorScheme(
    primary = androidx.compose.material3.ColorScheme().primary,
    onPrimary = androidx.compose.material3.ColorScheme().onPrimary,
    primaryContainer = androidx.compose.material3.ColorScheme().primaryContainer,
    onPrimaryContainer = androidx.compose.material3.ColorScheme().onPrimaryContainer,
    secondary = androidx.compose.material3.ColorScheme().secondary,
    onSecondary = androidx.compose.material3.ColorScheme().onSecondary,
    secondaryContainer = androidx.compose.material3.ColorScheme().secondaryContainer,
    onSecondaryContainer = androidx.compose.material3.ColorScheme().onSecondaryContainer,
    tertiary = androidx.compose.material3.ColorScheme().tertiary,
    onTertiary = androidx.compose.material3.ColorScheme().onTertiary,
    tertiaryContainer = androidx.compose.material3.ColorScheme().tertiaryContainer,
    onTertiaryContainer = androidx.compose.material3.ColorScheme().onTertiaryContainer,
    error = androidx.compose.material3.ColorScheme().error,
    onError = androidx.compose.material3.ColorScheme().onError,
    errorContainer = androidx.compose.material3.ColorScheme().errorContainer,
    onErrorContainer = androidx.compose.material3.ColorScheme().onErrorContainer,
    background = androidx.compose.material3.ColorScheme().background,
    onBackground = androidx.compose.material3.ColorScheme().onBackground,
    surface = androidx.compose.material3.ColorScheme().surface,
    onSurface = androidx.compose.material3.ColorScheme().onSurface,
    surfaceVariant = androidx.compose.material3.ColorScheme().surfaceVariant,
    onSurfaceVariant = androidx.compose.material3.ColorScheme().onSurfaceVariant,
    outline = androidx.compose.material3.ColorScheme().outline,
    outlineVariant = androidx.compose.material3.ColorScheme().outlineVariant,
    scrim = androidx.compose.material3.ColorScheme().scrim,
    inverseSurface = androidx.compose.material3.ColorScheme().inverseSurface,
    inverseOnSurface = androidx.compose.material3.ColorScheme().inverseOnSurface,
    inversePrimary = androidx.compose.material3.ColorScheme().inversePrimary,
    surfaceDim = androidx.compose.material3.ColorScheme().surfaceDim,
    surfaceBright = androidx.compose.material3.ColorScheme().surfaceBright,
    surfaceContainerLowest = androidx.compose.material3.ColorScheme().surfaceContainerLowest,
    surfaceContainerLow = androidx.compose.material3.ColorScheme().surfaceContainerLow,
    surfaceContainer = androidx.compose.material3.ColorScheme().surfaceContainer,
    surfaceContainerHigh = androidx.compose.material3.ColorScheme().surfaceContainerHigh,
    surfaceContainerHighest = androidx.compose.material3.ColorScheme().surfaceContainerHighest
)

val DarkColorScheme = darkColorScheme(
    primary = androidx.compose.material3.ColorScheme().primary,
    onPrimary = androidx.compose.material3.ColorScheme().onPrimary,
    primaryContainer = androidx.compose.material3.ColorScheme().primaryContainer,
    onPrimaryContainer = androidx.compose.material3.ColorScheme().onPrimaryContainer,
    secondary = androidx.compose.material3.ColorScheme().secondary,
    onSecondary = androidx.compose.material3.ColorScheme().onSecondary,
    secondaryContainer = androidx.compose.material3.ColorScheme().secondaryContainer,
    onSecondaryContainer = androidx.compose.material3.ColorScheme().onSecondaryContainer,
    tertiary = androidx.compose.material3.ColorScheme().tertiary,
    onTertiary = androidx.compose.material3.ColorScheme().onTertiary,
    tertiaryContainer = androidx.compose.material3.ColorScheme().tertiaryContainer,
    onTertiaryContainer = androidx.compose.material3.ColorScheme().onTertiaryContainer,
    error = androidx.compose.material3.ColorScheme().error,
    onError = androidx.compose.material3.ColorScheme().onError,
    errorContainer = androidx.compose.material3.ColorScheme().errorContainer,
    onErrorContainer = androidx.compose.material3.ColorScheme().onErrorContainer,
    background = androidx.compose.material3.ColorScheme().background,
    onBackground = androidx.compose.material3.ColorScheme().onBackground,
    surface = androidx.compose.material3.ColorScheme().surface,
    onSurface = androidx.compose.material3.ColorScheme().onSurface,
    surfaceVariant = androidx.compose.material3.ColorScheme().surfaceVariant,
    onSurfaceVariant = androidx.compose.material3.ColorScheme().onSurfaceVariant,
    outline = androidx.compose.material3.ColorScheme().outline,
    outlineVariant = androidx.compose.material3.ColorScheme().outlineVariant,
    scrim = androidx.compose.material3.ColorScheme().scrim,
    inverseSurface = androidx.compose.material3.ColorScheme().inverseSurface,
    inverseOnSurface = androidx.compose.material3.ColorScheme().inverseOnSurface,
    inversePrimary = androidx.compose.material3.ColorScheme().inversePrimary,
    surfaceDim = androidx.compose.material3.ColorScheme().surfaceDim,
    surfaceBright = androidx.compose.material3.ColorScheme().surfaceBright,
    surfaceContainerLowest = androidx.compose.material3.ColorScheme().surfaceContainerLowest,
    surfaceContainerLow = androidx.compose.material3.ColorScheme().surfaceContainerLow,
    surfaceContainer = androidx.compose.material3.ColorScheme().surfaceContainer,
    surfaceContainerHigh = androidx.compose.material3.ColorScheme().surfaceContainerHigh,
    surfaceContainerHighest = androidx.compose.material3.ColorScheme().surfaceContainerHighest
)